#include <iostream>
using namespace std;
main()
{
system ("color 2E");
cout<< "    pPPPPPPPPPPPPPPPP  		  																"<< endl;
cout<< "    PP                PP       AA AA AA AA AA            CCCCCCCCCCCCCCCC   MM		                MM MM	   AA AA AA AA		 NN 		       NN"<< endl;
cout<< "    PP                  PP   AA		     AA	       CC		    MM  MM	             MM    MM	 AA	       AA      NN   NN		       NN "<< endl;
cout<< "    PP                   PP AA		      AA     CC	          	    MM	  MM	           MM      MM	AA	        AA    NN      NN	       NN"<< endl;
cout<< "    PP                  PP AA 		      AA   CC		            MM	     MM	         MM	   MM  AA		 AA   NN	NN	       NN"<< endl;	
cout<< "    PP                 PP  AA	              AA  CC			    MM	        MM    MM           MM  AA		 AA   NN	 NN	       NN"<< endl;
cout<< "    PPPPPPPPPPPPPPPP PP	   AA		      AA CC			    MM		   MM	           MM  AA		 AA   NN	   NN	       NN"<< endl;
cout<< "    PP                     AA                 AA CC                         MM                             MM  AA    		 AA   NN	    NN	       NN"<< endl;
cout<< "    PP		           AA  AAAAAAAAAAAA   AA CC		            MM				   MM  AA  AAAAAAAAAAAA	 AA   NN             NN	       NN"<< endl;
cout<< "    PP			   AA		      AA CC		            MM			           MM  AA      		 AA   NN	      NN       NN"<< endl;
cout<< "    PP			   AA		      AA CC 		            MM				   MM  AA		 AA   NN	       NN      NN"<< endl;
cout<< "    PP		           AA		      AA  CC			    MM				   MM  AA		 AA   NN	        NN     NN"<< endl;
cout<< "    PP			   AA		      AA   CC			    MM			           MM  AA		 AA   NN		 NN    NN"<< endl;
cout<< "    PP		           AA		      AA    CC			    MM			           MM  AA		 AA   NN		  NN   NN"<< endl;
cout<< "    PP		           AA		      AA      CC		    MM				   MM  AA		 AA   NN		   NN  NN"<< endl;
cout<< "    PP                     AA                 AA        CCCCCCCCCCCCCCCCC   MM                             MM  AA       	 AA   NN		     NN	 "<< endl;
}
